### PR TITLE
Add Vivian's song

### PR DESCRIPTION
**Pull request by viviancreates**

### CODE REVIEW

**Review by bibimbop123 — APPROVED** [review]

**Review by merrillhuang — CHANGES_REQUESTED** [review]
Looks like your code failed the formatting test and needs fixing?

**Review by Ritumka — APPROVED** [review]
Cool!

**Review by merrillhuang — APPROVED** [review]
Looks good!

**Review by Ritumka — APPROVED** [review]
Cool!

**Pull request merged**
